-- Email Drafts: AI-generated reply drafts with optional grounding citations.
-- `source` distinguishes between drafts generated by our existing Azure OpenAI
-- pipeline and the new Copilot-RAG pipeline that grounds on M365 content.

CREATE TABLE IF NOT EXISTS email_drafts (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    user_id UUID REFERENCES users(id) ON DELETE SET NULL,

    -- Foreign key to email (as string — emails themselves come from Graph, not
    -- a local emails table). We store the Graph message id.
    email_id VARCHAR(512) NOT NULL,
    email_subject VARCHAR(1000),

    -- Which pipeline produced this draft
    source VARCHAR(32) NOT NULL,
    -- Values: 'azure_openai', 'copilot_rag'

    draft_text TEXT NOT NULL,

    -- Array of citations: [{ title, url, source, snippet }]
    -- `source` ∈ { 'teams', 'sharepoint', 'onedrive', 'email', 'other' }
    citations JSONB NOT NULL DEFAULT '[]',

    -- Token / cost tracking
    tokens_prompt INTEGER DEFAULT 0,
    tokens_completion INTEGER DEFAULT 0,
    estimated_cost_usd NUMERIC(10, 6) DEFAULT 0,
    processing_time_ms INTEGER,

    -- Additional metadata (model name, retrieval doc count, etc.)
    metadata JSONB DEFAULT '{}',

    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_email_drafts_tenant_email
    ON email_drafts (tenant_id, email_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_email_drafts_source
    ON email_drafts (tenant_id, source);

DROP TRIGGER IF EXISTS update_email_drafts_updated_at ON email_drafts;
CREATE TRIGGER update_email_drafts_updated_at
    BEFORE UPDATE ON email_drafts
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();
